Ext.define('YZSoft.src.flowchart.point.link.CornerPoint', {
    extend: 'YZSoft.src.flowchart.point.HotPoint',
    isCornerPoint: true,
    src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwNC8xNS8xNYld3z8AAAAYdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3Jrc0+zH04AAAA9SURBVAiZZY6xEYBADMPk7L+zKPiAOdwkPqlwVDZJVLN9GuC5DRcAtBDgBZ3AqCF/oGbgfh7hgM+gFXrtBSCbIgc8qjKpAAAAAElFTkSuQmCC',
    srchot: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwNC8yNC8xNXZBwooAAAAYdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3Jrc0+zH04AAABISURBVAiZbY5JCoBAAMMSP+748niYcQN7KiSUWuEh7aHGQFa2q6gFMAiYcvWAS5ySAh/wFrZKfwADqWDAWgioonoO3QvrrYecxNQp/WSmk+MAAAAASUVORK5CYII=',
    width: 7,
    height:7
});