
Ext.define('YZSoft.report.rpt.store.MSChartTypeStore', {
    extend: 'Ext.data.Store',
    fields: ['value'],
    data: [
        { value: 'Area' },
        { value: 'Bar' },
        { value: 'BoxPlot' },
        { value: 'Bubble' },
        { value: 'Candlestick' },
        { value: 'Column' },
        { value: 'Doughnut' },
        { value: 'ErrorBar' },
        { value: 'FastLine' },
        { value: 'FastPoint' },
        { value: 'Funnel' },
        { value: 'Kagi' },
        { value: 'Line' },
        { value: 'Pie' },
        { value: 'Point' },
        { value: 'PointAndFigure' },
        { value: 'Polar' },
        { value: 'Pyramid' },
        { value: 'Radar' },
        { value: 'Range' },
        { value: 'RangeBar' },
        { value: 'RangeColumn' },
        { value: 'Renko' },
        { value: 'Spline' },
        { value: 'SplineArea' },
        { value: 'SplineRange' },
        { value: 'StackedArea' },
        { value: 'StackedArea100' },
        { value: 'StackedBar' },
        { value: 'StackedBar100' },
        { value: 'StackedColumn' },
        { value: 'StackedColumn100' },
        { value: 'StepLine' },
        { value: 'Stock' },
        { value: 'ThreeLineBreak' }
    ]
});